import { useMemo, useState } from "react";
import { ArrowUpDown, ChevronRight, Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { formatNumber, statusFor, type District } from "@/features/mis/mock-service";
type SortKey = "name" | "totalStudents" | "activeStudents" | "engagement" | "learningHours";
export function DistrictTable({ districts, onSelect, limit }: { districts: District[]; onSelect?: (id: string) => void; limit?: number }) {
  const [query, setQuery] = useState(""); const [sort, setSort] = useState<SortKey>("engagement"); const [asc, setAsc] = useState(false); const [showAll, setShowAll] = useState(false);
  const rows = useMemo(() => districts.filter(d => d.name.toLowerCase().includes(query.toLowerCase())).sort((a,b) => { const av = a[sort], bv = b[sort]; return (typeof av === "string" ? av.localeCompare(String(bv)) : Number(av)-Number(bv)) * (asc ? 1 : -1); }), [districts, query, sort, asc]);
  const visible = limit && !showAll ? rows.slice(0, limit) : rows;
  const changeSort = (key: SortKey) => { if (key === sort) setAsc(v => !v); else { setSort(key); setAsc(false); } };
  return <div><div className="relative mb-4 max-w-xs"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search district" className="pl-9" /></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-y border-border bg-table-head text-[10px] uppercase text-muted-foreground"><th className="px-3 py-3">#</th>{(["name","totalStudents","activeStudents","engagement","learningHours"] as SortKey[]).map(key => <th key={key} className="px-3 py-3"><button className="inline-flex items-center gap-1 font-semibold" onClick={() => changeSort(key)}>{key === "name" ? "District" : key.replace(/([A-Z])/g," $1")}<ArrowUpDown className="size-3" /></button></th>)}<th className="px-3 py-3">Status</th><th /></tr></thead><tbody>{visible.map((d, i) => { const status = statusFor(d.engagement); return <tr key={d.id} onClick={() => onSelect?.(d.id)} className={`border-b border-border transition-colors ${onSelect ? "cursor-pointer hover:bg-accent/60" : ""}`}><td className="px-3 py-3 text-muted-foreground">{i+1}</td><td className="px-3 py-3 font-semibold">{d.name}</td><td className="px-3 py-3 tabular-nums">{formatNumber(d.totalStudents)}</td><td className="px-3 py-3 tabular-nums">{formatNumber(d.activeStudents)}</td><td className="px-3 py-3 font-semibold tabular-nums">{d.engagement}%</td><td className="px-3 py-3 tabular-nums">{formatNumber(d.learningHours)}</td><td className="px-3 py-3"><span className={`rounded-sm bg-${status.toLowerCase()}-soft px-2 py-1 text-[10px] font-bold text-${status.toLowerCase()}`}>{status}</span></td><td className="px-3 py-3"><ChevronRight className="size-4 text-muted-foreground" /></td></tr>; })}</tbody></table></div>{limit && rows.length > limit && <button onClick={() => setShowAll(v => !v)} className="mt-4 text-xs font-semibold text-primary hover:underline">{showAll ? "Show fewer districts" : `View all ${rows.length} districts`}</button>}</div>;
}
