import { ArrowUpRight, Bot, ExternalLink, Microscope, Sigma } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PROGRAM_LINKS } from "@/config/program-links";
import { formatNumber, type LearningProgram } from "@/features/mis/mock-service";
const icons = { "ai-ml": Bot, neet: Microscope, jee: Sigma } as const;
export function ProgramCards({ programs, detailed = false }: { programs: LearningProgram[]; detailed?: boolean }) {
  return <div className={`grid gap-3 ${detailed ? "xl:grid-cols-3" : "lg:grid-cols-3"}`}>{programs.map(program => { const Icon = icons[program.id]; return <article key={program.id} className="group overflow-hidden rounded-sm border border-border bg-card transition-colors hover:border-input">
    <div className={`relative flex items-center justify-center overflow-hidden bg-${program.color}-soft ${detailed ? "h-32" : "h-20"}`}><div className={`absolute inset-0 program-pattern-${program.id}`} /><Icon className={`relative ${detailed ? "size-12" : "size-9"} text-${program.color}`} strokeWidth={1.4} /></div>
    <div className={detailed ? "p-4" : "p-3"}><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-bold">{program.name}</h3><p className="mt-0.5 text-[10px] text-muted-foreground">{program.fullName}</p></div><ArrowUpRight className="size-4 text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></div>{detailed && <p className="mt-3 text-xs leading-5 text-muted-foreground">{program.description}</p>}<div className="mt-3 grid grid-cols-2 gap-3"><div><p className="text-[9px] uppercase text-muted-foreground">Enrolled</p><p className="mt-0.5 text-xs font-bold">{formatNumber(program.enrolledStudents)}</p></div>{detailed && <div><p className="text-[9px] uppercase text-muted-foreground">Active</p><p className="mt-0.5 text-xs font-bold">{formatNumber(program.activeStudents)}</p></div>}<div><p className="text-[9px] uppercase text-muted-foreground">Engagement</p><p className="mt-0.5 text-xs font-bold">{program.engagement}%</p></div>{detailed && <><div><p className="text-[9px] uppercase text-muted-foreground">Completion</p><p className="mt-0.5 text-xs font-bold">{program.completion}%</p></div><div><p className="text-[9px] uppercase text-muted-foreground">Learning Hours</p><p className="mt-0.5 text-xs font-bold">{formatNumber(program.learningHours)}</p></div></>}</div>
    </div><div className={`flex items-center border-t border-border ${detailed ? "p-4" : "p-3 pt-2"}`}><Button size="sm" variant="outline" asChild className="w-full rounded-sm whitespace-nowrap"><a href={PROGRAM_LINKS[program.linkKey]} target="_blank" rel="noreferrer"><ExternalLink />Explore on Klassroom</a></Button></div>
  </article>; })}</div>;
}
