import { ArrowUpRight, Bot, ExternalLink, Microscope, Sigma, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PROGRAM_LINKS } from "@/config/program-links";
import { formatNumber, type LearningProgram } from "@/features/mis/mock-service";
const icons = { "ai-ml": Bot, neet: Microscope, jee: Sigma } as const;
export function ProgramCards({ programs, detailed = false }: { programs: LearningProgram[]; detailed?: boolean }) {
  return <div className={`grid gap-4 ${detailed ? "xl:grid-cols-3" : ""}`}>{programs.map(program => { const Icon = icons[program.id]; return <article key={program.id} className={`group overflow-hidden rounded-lg border border-border bg-card shadow-mis transition-all hover:border-primary/30 hover:shadow-mis-raised ${detailed ? "" : "grid md:grid-cols-[132px_1fr_auto]"}`}>
    <div className={`relative flex min-h-28 items-center justify-center overflow-hidden bg-${program.color}-soft ${detailed ? "h-40" : ""}`}><div className={`absolute inset-0 program-pattern-${program.id}`} /><Icon className={`relative size-14 text-${program.color}`} strokeWidth={1.4} /></div>
    <div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-base font-bold">{program.name}</h3><p className="mt-0.5 text-xs text-muted-foreground">{program.fullName}</p></div><ArrowUpRight className="size-4 text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></div>{detailed && <p className="mt-4 text-sm leading-6 text-muted-foreground">{program.description}</p>}<div className={`mt-4 grid gap-3 ${detailed ? "grid-cols-2" : "grid-cols-2 sm:grid-cols-3"}`}><div><p className="text-[10px] uppercase text-muted-foreground">Enrolled</p><p className="mt-1 text-sm font-bold">{formatNumber(program.enrolledStudents)}</p></div>{detailed && <div><p className="text-[10px] uppercase text-muted-foreground">Active</p><p className="mt-1 text-sm font-bold">{formatNumber(program.activeStudents)}</p></div>}<div><p className="text-[10px] uppercase text-muted-foreground">Engagement</p><p className="mt-1 text-sm font-bold">{program.engagement}%</p></div><div className={detailed ? "" : "hidden sm:block"}><p className="text-[10px] uppercase text-muted-foreground">{detailed ? "Completion" : "Students"}</p><p className="mt-1 text-sm font-bold">{detailed ? `${program.completion}%` : formatNumber(program.enrolledStudents)}</p></div>{detailed && <div><p className="text-[10px] uppercase text-muted-foreground">Learning Hours</p><p className="mt-1 text-sm font-bold">{formatNumber(program.learningHours)}</p></div>}</div>
    </div><div className={`flex items-center p-5 ${detailed ? "border-t border-border" : "md:justify-end"}`}><Button variant="outline" asChild className="w-full whitespace-nowrap md:w-auto"><a href={PROGRAM_LINKS[program.linkKey]} target="_blank" rel="noreferrer"><ExternalLink />Explore on Klassroom</a></Button></div>
  </article>; })}</div>;
}
