import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { ArrowDown, ArrowRight, BookOpen, Brain, Building2, Calculator, Check, ClipboardCheck, Download, GraduationCap, KeyRound, Landmark, MessageSquare, PlayCircle, Scale, ShieldCheck, Stethoscope, Target, Trophy, Tv2, UserCheck, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PROGRAM_LINKS } from '@/config/program-links';
import learningPhoto from '@/assets/bocw-learning.jpg';

export const Route = createFileRoute('/home')({
  head: () => ({ meta: [
    { title: 'Maharashtra Digital Learning — MBOCWWB | Free Education for BOCW Worker Children' },
    { name: 'description', content: 'MBOCWWB digital education for children of registered construction workers: NEET, JEE and AI/ML across all 36 districts of Maharashtra.' },
    { property: 'og:title', content: 'Maharashtra Digital Learning — MBOCWWB' },
    { property: 'og:description', content: 'Free education for BOCW worker children across Maharashtra. Explore the digital learning proposal and MIS.' },
    { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' },
  ] }), component: PublicHome,
});
const impact = [ { value: 6700000, suffix: '+', label: 'Registered BOCW Workers', icon: Users }, { value: 124580, suffix: '', label: 'Students Enrolled', icon: GraduationCap }, { value: 384210, suffix: '', label: 'Learning Hours Logged', icon: BookOpen }, { value: 36, suffix: '', label: 'Districts Covered', icon: Building2 } ];
const policies = [
  { icon: BookOpen, title: 'National Education Policy (NEP) 2020', tag: 'Central Government', tone: 'text-blue bg-blue-soft', point: 'Equity & Inclusion Mandate', text: 'NEP 2020 mandates equitable and inclusive education for all sections of society. This platform delivers standardised digital learning to the most economically vulnerable — children of unorganised sector construction workers.' },
  { icon: Scale, title: 'BOCW Act 1996 — Education Welfare', tag: 'Legal Mandate', tone: 'text-amber bg-amber-soft', point: 'Education Welfare Mandate', text: 'The BOCW welfare framework supports educational assistance for the children of registered construction workers. This initiative proposes a digital pathway to fulfil that welfare objective.' },
  { icon: Tv2, title: 'PM eVidya & DIKSHA', tag: 'Central Scheme', tone: 'text-green bg-green-soft', point: 'Digital India Vision', text: "India’s PM eVidya initiative promotes digital learning for all. This platform operates in the same spirit — providing structured, curriculum-aligned pre-recorded video content for competitive exam preparation at zero cost." },
  { icon: Landmark, title: 'Maharashtra State Education Mission', tag: 'State Government', tone: 'text-primary bg-primary-soft', point: 'Equal Opportunity', text: "Maharashtra’s state education vision emphasises skill-ready, exam-prepared youth from all socioeconomic backgrounds. NEET and JEE preparation is proposed for BOCW workers’ children across all 36 districts." },
];
const programs = [
  { icon: Stethoscope, title: 'NEET Preparation', badge: 'Medical Entrance', tone: 'text-green', bg: 'bg-green-soft', stripe: 'bg-green', enrolled: '18,720', engagement: '72%', videos: '620+', href: PROGRAM_LINKS.neet, text: 'Complete syllabus coverage for Physics, Chemistry, and Biology. Chapter-wise pre-recorded lectures, mock tests, and doubt-resolution for Class 11th & 12th students targeting MBBS/BDS admissions.' },
  { icon: Calculator, title: 'JEE Preparation', badge: 'Engineering Entrance', tone: 'text-blue', bg: 'bg-blue-soft', stripe: 'bg-blue', enrolled: '15,860', engagement: '69%', videos: '580+', href: PROGRAM_LINKS.jee, text: 'Full JEE Main & Advanced preparation with Physics, Chemistry, and Mathematics. Expert faculty, chapter-wise recordings, formula sheets, and practice problem sets for aspiring engineers.' },
  { icon: Brain, title: 'AI & Machine Learning', badge: 'Future Skills', tone: 'text-amber', bg: 'bg-amber-soft', stripe: 'bg-amber', enrolled: '12,450', engagement: '68%', videos: '240+', href: PROGRAM_LINKS.aiMl, text: 'Introduction to Artificial Intelligence and Machine Learning concepts. Designed for students across age groups to prepare them for India’s emerging technology-driven economy and careers of the future.' },
];
const steps = [
  { icon: UserCheck, title: 'BOCW Worker Registers', text: "Parent registers with the board. A child’s learning profile is created." },
  { icon: KeyRound, title: 'Child Gets Free Access', text: 'Student receives login credentials for mobile, tablet or computer.' },
  { icon: PlayCircle, title: 'Watches Video Lectures', text: 'Chapter-wise lectures by expert faculty, available anytime.' },
  { icon: ClipboardCheck, title: 'Takes Tests & Mocks', text: 'Chapter tests and full-length mock exams with results and analysis.' },
  { icon: MessageSquare, title: 'AI Tutor Resolves Doubts', text: 'Subject-specific support in Marathi, Hindi or English.' },
  { icon: Trophy, title: 'Scholarship & Exam Ready', text: 'Top performers considered for scholarships and exam readiness.' },
];
const districts = [ ['Mumbai',78], ['Pune',74], ['Nagpur',71], ['Nashik',64], ['Aurangabad',58], ['Nandurbar',47], ['Gadchiroli',43], ['Washim',44] ] as const;
const format = (n: number) => n.toLocaleString('en-IN');
function useCountUp(target: number, start: boolean) {
  const [count, setCount] = useState(target);
  useEffect(() => {
    if (!start || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    let frame = 0; const began = performance.now();
    const tick = (now: number) => { const p = Math.min((now - began) / 1600, 1); setCount(Math.floor(target * (1 - (1-p)**3))); if (p < 1) frame = requestAnimationFrame(tick); };
    frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame);
  }, [target, start]);
  return count;
}
function Counter({ value, label, suffix, start }: { value: number; label: string; suffix: string; start: boolean }) {
  const count = useCountUp(value, start);
  return <div className="min-w-0 px-4 py-2 text-center sm:border-r sm:border-government-bar-foreground/15"><div className="font-display text-3xl font-extrabold lg:text-4xl tabular-nums">{format(count)}{suffix}</div><div className="mt-2 text-[10px] font-semibold uppercase text-government-bar-foreground/65">{label}</div></div>;
}
function SectionHeading({ label, title, children }: { label: string; title: string; children: ReactNode }) {
  return <div className="mx-auto mb-9 max-w-3xl text-center"><p className="mb-3 text-xs font-bold uppercase text-primary">{label}</p><h2 className="text-2xl font-extrabold sm:text-3xl">{title}</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-muted-foreground">{children}</p></div>;
}
function PublicHome() {
  const strip = useRef<HTMLDivElement>(null); const [start, setStart] = useState(false);
  useEffect(() => { const element = strip.current; if (!element) return; const observer = new IntersectionObserver(([entry]) => { if (entry?.isIntersecting) { setStart(true); observer.disconnect(); } }, { threshold: .2 }); observer.observe(element); return () => observer.disconnect(); }, []);
  return <div className="text-foreground">
    <section className="home-hero relative border-b border-border" style={{ '--home-photo': `url(${learningPhoto})` } as CSSProperties}>
      <div className="relative mx-auto max-w-[1600px] px-5 py-12 sm:px-8 lg:py-16">
        <div className="max-w-xl lg:max-w-[48%]">
          <p className="mb-5 flex items-center gap-2 text-xs font-bold text-primary"><Landmark className="size-4" />Government of Maharashtra Initiative</p>
          <h1 className="text-4xl font-extrabold leading-tight">Digital Education for Children of Maharashtra’s Construction Workers</h1>
          <p className="mt-5 text-sm leading-7 text-muted-foreground">MBOCWWB is providing free, high-quality pre-recorded video lectures for NEET, JEE, and AI &amp; ML courses to children of registered BOCW workers — empowering Maharashtra’s labour families through education.</p>
          <div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold">{['100% Free for BOCW Worker Families','Covers 36 Districts of Maharashtra'].map(x => <span key={x} className="flex items-center gap-2"><Check className="size-4 text-green" />{x}</span>)}</div>
          <div className="mt-7 flex flex-wrap gap-3"><Button asChild className="h-11"><Link to="/auth">Enter MIS Dashboard<ArrowRight /></Link></Button><Button variant="outline" className="h-11 border-primary text-primary" onClick={() => document.getElementById('programs')?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' })}>Learn About the Program<ArrowDown /></Button></div>
          <p className="mt-5 text-[10px] text-muted-foreground">Digital Learning MIS · Programme proposal &amp; demonstration</p>
        </div>
      </div>
      <img src={learningPhoto} width={1536} height={1024} alt="Students studying science together with digital learning resources" className="block w-full lg:hidden" />
    </section>
    <section className="bg-card px-5 py-6 sm:px-8"><div className="mx-auto flex max-w-[1536px] flex-wrap items-center gap-x-8 gap-y-5"><h2 className="text-xs font-bold uppercase text-primary">Program at a Glance</h2><div className="grid flex-1 grid-cols-2 gap-5 md:grid-cols-4">{impact.map(s => <div key={s.label} className="flex items-start gap-3"><s.icon className="mt-1 size-5 shrink-0 text-primary" /><div><p className="text-lg font-extrabold">{format(s.value)}{s.suffix}{s.value === 36 && ' of 36'}</p><p className="text-[11px] text-muted-foreground">{s.label === 'Students Enrolled' ? 'Students Currently Enrolled' : s.label}</p></div></div>)}</div><div className="border-l-2 border-primary pl-4"><p className="flex items-center gap-2 text-lg font-bold text-green"><ShieldCheck className="size-5" />₹0 cost to students</p><p className="text-[10px] text-muted-foreground">Fully funded by Maharashtra Government</p></div></div></section>
    <section ref={strip} className="bg-government-bar py-9 text-government-bar-foreground"><div className="mx-auto grid max-w-[1440px] grid-cols-2 gap-y-5 sm:grid-cols-5">{impact.map(s => <Counter key={s.label} {...s} start={start} />)}<div className="px-4 py-2 text-center"><p className="text-4xl font-extrabold text-warning">₹0</p><p className="mt-2 text-[10px] uppercase text-government-bar-foreground/65">Cost to Students</p><p className="mt-1 text-xs text-warning">Govt. Funded</p></div></div></section>
    <section id="policy" className="home-section bg-card px-5 py-14 sm:px-8"><div className="mx-auto max-w-[1200px]"><SectionHeading label="Policy Alignment" title="Aligned with Maharashtra & Central Government Vision">This initiative supports the education and inclusion objectives of national and state-level policy frameworks.</SectionHeading><div className="grid gap-5 md:grid-cols-2">{policies.map(p => <article key={p.title} className="rounded-lg border border-border p-6 shadow-mis transition-shadow hover:shadow-mis-raised"><div className="flex items-center gap-3"><p.icon className="size-6 shrink-0 text-primary" /><span className={`rounded-sm px-2 py-1 text-[10px] font-bold ${p.tone}`}>{p.tag}</span></div><h3 className="mt-4 text-lg font-bold">{p.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{p.text}</p><p className="mt-4 border-t border-border pt-3 text-xs font-semibold text-primary">{p.point}</p></article>)}</div><blockquote className="mt-7 flex gap-4 border-l-4 border-primary bg-primary-soft p-6 text-sm leading-7"><Target className="mt-1 size-6 shrink-0 text-primary" />“This is not just an education platform. It is a welfare commitment being fulfilled digitally — ensuring construction workers’ families receive the educational upliftment they deserve.”</blockquote></div></section>
    <section id="programs" className="home-section px-5 py-14 sm:px-8"><div className="mx-auto max-w-[1200px]"><SectionHeading label="Learning Programs" title="Three Pathways. One Mission — Upliftment.">Pre-recorded video lectures delivered by expert faculty, accessible anytime, on any device.</SectionHeading><div className="grid gap-5 md:grid-cols-3">{programs.map(p => <article key={p.title} className="flex flex-col overflow-hidden rounded-lg border border-border bg-card shadow-mis"><div className={`h-1.5 ${p.stripe}`} /><div className="flex flex-1 flex-col p-6"><div className={`mb-4 flex size-12 items-center justify-center rounded-lg ${p.bg} ${p.tone}`}><p.icon className="size-6" /></div><p className={`text-[10px] font-bold uppercase ${p.tone}`}>{p.badge}</p><h3 className="mt-2 text-xl font-extrabold">{p.title}</h3><p className="mt-3 flex-1 text-sm leading-7 text-muted-foreground">{p.text}</p><div className="my-5 grid grid-cols-3 gap-2 border-y border-border py-4">{[[p.enrolled,'Enrolled'],[p.engagement,'Engagement'],[p.videos,'Video Lectures']].map(([v,l]) => <div key={l}><p className="text-base font-bold">{v}</p><p className="mt-1 text-[10px] text-muted-foreground">{l}</p></div>)}</div><Button asChild variant="outline" className={p.tone}><a href={p.href} target="_blank" rel="noopener noreferrer">Explore on Klassroom<ArrowRight /></a></Button></div></article>)}</div><p className="mt-5 text-center text-xs text-muted-foreground">Content provided by our learning partner Klassroom. Technology platform by Arceus InfoTech.</p></div></section>
    <section className="bg-card px-5 py-14 sm:px-8"><div className="mx-auto max-w-[1400px]"><SectionHeading label="Student Journey" title="From a Worker’s Home to an Exam Hall">See how a construction worker’s child goes from registration to exam-readiness on this platform.</SectionHeading><ol className="grid gap-7 sm:grid-cols-2 lg:grid-cols-6">{steps.map((s,i) => <li key={s.title} className="relative border-t-2 border-dashed border-border pt-5"><div className="relative mb-4 flex size-12 items-center justify-center rounded-full bg-primary-soft text-primary"><s.icon className="size-6" /><span className="absolute -right-1 -top-1 flex size-5 items-center justify-center rounded-full bg-primary text-[10px] font-bold text-primary-foreground">{i+1}</span></div><h3 className="text-sm font-bold">{s.title}</h3><p className="mt-2 text-xs leading-6 text-muted-foreground">{s.text}</p></li>)}</ol></div></section>
    <section className="px-5 py-14 sm:px-8"><div className="mx-auto grid max-w-[1100px] items-center gap-10 md:grid-cols-2"><div><p className="text-xs font-bold uppercase text-primary">Parent Engagement</p><h2 className="mt-3 text-3xl font-extrabold">Parents Are Never Left Behind</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">The proposed parent engagement service provides regular SMS/WhatsApp updates in Marathi about their child’s learning progress — directly on their mobile phone. No app download required.</p><ul className="my-6 space-y-3 text-sm">{['Weekly progress summary in Marathi','Mock test scores and attendance alerts','Scholarship eligibility notifications'].map(x => <li key={x} className="flex gap-2"><Check className="size-5 text-green" />{x}</li>)}</ul><blockquote className="border-l-4 border-amber bg-amber-soft p-5 text-sm leading-7">“We built this for parents who may not own a laptop or understand English — the worker who builds our cities deserves to know their child is being taken care of.”</blockquote></div><div className="mx-auto w-full max-w-[300px] rounded-[2rem] border-4 border-foreground bg-card p-3 shadow-mis-raised"><div className="mx-auto mb-3 h-1 w-14 rounded-full bg-foreground" /><div className="flex items-center gap-2 border-b border-border p-3 text-sm font-bold"><MessageSquare className="size-5 text-green" />MBOCWWB Gov<ShieldCheck className="size-4 text-green" /></div><div className="space-y-3 bg-green-soft p-3">{[
  ['📚 MBOCWWB शिक्षण अहवाल\n\nप्रिय पालक,\nआपल्या मुलाने या आठवड्यात 4 तास अभ्यास केला.\n\nNEET Mock Test: 78/180 🎯\n\n— महाराष्ट्र शासन','Today, 08:15 AM'],
  ['🏆 अभिनंदन!\nआपल्या मुलाने 7-Day Streak पूर्ण केली.\nTop 20% in Pune District 📊','Yesterday, 10:30 AM'],
  ['💰 शिष्यवृत्ती अपडेट:\nआपला मुलगा/मुलगी BOCW शिष्यवृत्तीसाठी पात्र आहे!\nअर्ज करण्यासाठी लॉगिन करा.','Mon, 09:00 AM'],
].map(([text,time]) => <div key={time} className="rounded-lg border border-green/20 bg-card p-3"><p className="whitespace-pre-line text-xs leading-6">{text}</p><p className="mt-2 text-right text-[9px] text-muted-foreground">{time}</p></div>)}</div><p className="pt-3 text-center text-[10px] text-muted-foreground">Illustrative parent notification</p></div></div></section>
    <section className="bg-card px-5 py-14 sm:px-8"><div className="mx-auto grid max-w-[1200px] items-center gap-10 md:grid-cols-2"><div><Building2 className="mb-4 size-8 text-primary" /><h2 className="text-3xl font-extrabold">Covering All 36 Districts of Maharashtra</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">From Mumbai to Gadchiroli — every district is part of this mission. The MIS brings district engagement and student performance together for informed decisions.</p><div className="mt-6 space-y-3 text-xs"><p className="flex items-center gap-2"><span className="size-2.5 rounded-full bg-green" />High Engagement (≥70%)</p><p className="flex items-center gap-2"><span className="size-2.5 rounded-full bg-amber" />Medium Engagement (50%–70%)</p><p className="flex items-center gap-2"><span className="size-2.5 rounded-full bg-red" />Low Engagement (&lt;50%) — special intervention</p></div><p className="mt-6 border-l-4 border-amber bg-amber-soft p-4 text-sm font-semibold">6 districts flagged for special engagement intervention in this proposal</p></div><div className="overflow-hidden rounded-lg border border-border"><table className="w-full text-left text-sm"><caption className="bg-table-head px-5 py-3 text-left text-xs font-bold uppercase text-muted-foreground">District engagement · Demonstration data</caption><thead className="border-y border-border text-xs text-muted-foreground"><tr><th className="px-5 py-3">District</th><th className="px-3 py-3">Engagement</th><th className="px-3 py-3">Status</th></tr></thead><tbody>{districts.map(([name,value]) => <tr key={name} className="border-b border-border"><td className="px-5 py-3 font-medium">{name}</td><td className="px-3 py-3 tabular-nums">{value}%</td><td className="px-3 py-3"><span className={`rounded-sm px-2 py-1 text-[10px] font-semibold ${value>=70 ? 'bg-green-soft text-green' : value>=50 ? 'bg-amber-soft text-amber' : 'bg-red-soft text-red'}`}>{value>=70 ? 'High' : value>=50 ? 'Medium' : 'Needs Attention'}</span></td></tr>)}</tbody></table><Button asChild variant="link" className="m-2"><Link to="/auth">View Full District Analytics<ArrowRight /></Link></Button></div></div></section>
    <section className="home-final px-5 py-14 text-center text-primary-foreground"><h2 className="text-3xl font-extrabold sm:text-4xl">Ready to Monitor. Ready to Empower.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-primary-foreground/80">Access the MIS dashboard to track district-wise engagement, monitor student performance, and generate reports.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Button asChild variant="secondary" className="h-11 bg-card text-primary hover:bg-card/90"><Link to="/auth">Enter MIS Dashboard<ArrowRight /></Link></Button><Button asChild variant="outline" className="h-11 border-primary-foreground/50 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><a href="/mbocwwb-digital-learning-proposal.pdf" download><Download />Download Proposal PDF</a></Button></div><div className="mt-6 flex flex-wrap justify-center gap-6 text-[11px] text-primary-foreground/70"><span className="flex items-center gap-1.5"><ShieldCheck className="size-3.5" />Secure Government Portal</span><span className="flex items-center gap-1.5"><ClipboardCheck className="size-3.5" />Programme Proposal</span><span className="flex items-center gap-1.5"><Landmark className="size-3.5" />Govt. of Maharashtra</span></div></section>
  </div>;
}
