import { createFileRoute } from "@tanstack/react-router";
import { Download, Eye, FileBarChart, FileSpreadsheet, Printer } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PageHeader } from "@/components/mis/page-header";
import { SectionCard } from "@/components/mis/section-card";
import { districtOptions, programOptions, timeOptions } from "@/features/mis/filter-options";
import { formatNumber, misService, statusFor } from "@/features/mis/mock-service";

export const Route = createFileRoute("/reports")({
  head: () => ({ meta: [{ title: "Reports & Insights | Maharashtra Learning MIS" }, { name: "description", content: "Generate and review district, program and participation reports for Maharashtra digital learning." }, { property: "og:title", content: "Reports & Insights | Maharashtra Learning MIS" }, { property: "og:description", content: "Government learning engagement reports and insights." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ReportsPage,
});
const reportTypes = ["District Engagement Report", "Course-wise Engagement Report", "Low Engagement Areas Report", "Student Participation Summary", "Monthly Engagement Summary"];
function ReportsPage() {
  const [filters, setFilters] = useState({ type: reportTypes[0], district: "all", program: "all", period: "30d" }); const [generated, setGenerated] = useState(true);
  const rows = useMemo(() => misService.getDistricts().filter(d => filters.district === "all" || d.id === filters.district).filter(d => filters.type !== "Low Engagement Areas Report" || d.engagement < 50), [filters]);
  const exportCsv = () => { const csv = ["District,Total Students,Active Students,Engagement,Learning Hours,Status", ...rows.map(d => `"${d.name}",${d.totalStudents},${d.activeStudents},${d.engagement},${d.learningHours},${statusFor(d.engagement)}`)].join("\n"); const blob = new Blob([csv], { type: "text/csv" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "maharashtra-learning-report.csv"; a.click(); URL.revokeObjectURL(url); };
  return <><PageHeader title="Reports & Insights" subtitle="Generate and review learning engagement reports." /><div className="space-y-6 p-4 sm:p-6 xl:p-8"><SectionCard title="Report Builder" subtitle="Choose reporting parameters to prepare a demonstration report"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><ReportField label="Report Type" value={filters.type} options={reportTypes.map(x => ({ value:x,label:x }))} onChange={v => setFilters({...filters,type:v})} /><ReportField label="District" value={filters.district} options={districtOptions} onChange={v => setFilters({...filters,district:v})} /><ReportField label="Learning Program" value={filters.program} options={programOptions} onChange={v => setFilters({...filters,program:v})} /><ReportField label="Time Period" value={filters.period} options={timeOptions} onChange={v => setFilters({...filters,period:v})} /></div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={() => setGenerated(true)}><Eye />View Report</Button><Button variant="outline" onClick={() => window.print()}><Printer />Export PDF</Button><Button variant="outline" onClick={exportCsv}><FileSpreadsheet />Export Excel</Button></div></SectionCard>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{reportTypes.map((type, i) => <button key={type} onClick={() => { setFilters({...filters,type}); setGenerated(true); }} className={`rounded-lg border p-4 text-left shadow-mis transition-colors hover:border-primary/40 ${filters.type === type ? "border-primary bg-primary-soft" : "border-border bg-card"}`}><div className={`grid size-9 place-items-center rounded-md ${i === 2 ? "bg-destructive-soft text-destructive" : "bg-blue-soft text-blue"}`}><FileBarChart className="size-4" /></div><p className="mt-3 text-xs font-bold leading-5">{type}</p><p className="mt-1 text-[10px] text-muted-foreground">Demo report · Updated today</p></button>)}</div>
    {generated && <SectionCard title={filters.type} subtitle={`${rows.length} district records · Demo data only`} action={<Button size="sm" variant="outline" onClick={exportCsv}><Download />Download CSV</Button>}><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr className="border-y border-border bg-table-head text-[10px] uppercase text-muted-foreground"><th className="px-3 py-3">District</th><th>Total Students</th><th>Active Students</th><th>Engagement</th><th>Learning Hours</th><th>Status</th></tr></thead><tbody>{rows.map(d => <tr key={d.id} className="border-b border-border"><td className="px-3 py-3 font-semibold">{d.name}</td><td>{formatNumber(d.totalStudents)}</td><td>{formatNumber(d.activeStudents)}</td><td className="font-semibold">{d.engagement}%</td><td>{formatNumber(d.learningHours)}</td><td><span className={`rounded-sm bg-${statusFor(d.engagement).toLowerCase()}-soft px-2 py-1 text-[10px] font-bold text-${statusFor(d.engagement).toLowerCase()}`}>{statusFor(d.engagement)}</span></td></tr>)}</tbody></table></div></SectionCard>}</div></>;
}
function ReportField({ label, value, options, onChange }: { label:string; value:string; options:{value:string;label:string}[]; onChange:(v:string)=>void }) { return <label><span className="mb-1.5 block text-[11px] font-semibold uppercase text-muted-foreground">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{options.map(o => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>; }
