// Official 36 Districts of Maharashtra and their respective talukas (administrative subdivisions)
// Sourced from Maharashtra State Revenue & Forest Department administrative registry.

export interface DistrictTalukaDefinition {
  id: string;
  name: string;
  code: string;
  division: "Konkan" | "Pune" | "Nashik" | "Chhatrapati Sambhajinagar" | "Amravati" | "Nagpur";
  headquarters: string;
  baseStudents: number;
  baseEngagement: number;
  talukas: string[];
}

export const MAHARASHTRA_36_DISTRICTS: DistrictTalukaDefinition[] = [
  // --- KONKAN DIVISION (7 districts) ---
  {
    id: "mumbai",
    name: "Mumbai City",
    code: "MUM",
    division: "Konkan",
    headquarters: "Mumbai",
    baseStudents: 18240,
    baseEngagement: 78.6,
    talukas: ["Mumbai City"],
  },
  {
    id: "mumbai-suburban",
    name: "Mumbai Suburban",
    code: "MSU",
    division: "Konkan",
    headquarters: "Bandra",
    baseStudents: 24650,
    baseEngagement: 79.4,
    talukas: ["Andheri", "Borivali", "Kurla"],
  },
  {
    id: "thane",
    name: "Thane",
    code: "THA",
    division: "Konkan",
    headquarters: "Thane",
    baseStudents: 14760,
    baseEngagement: 73.1,
    talukas: ["Thane", "Kalyan", "Murbad", "Bhiwandi", "Shahapur", "Ulhasnagar", "Ambarnath"],
  },
  {
    id: "palghar",
    name: "Palghar",
    code: "PLG",
    division: "Konkan",
    headquarters: "Palghar",
    baseStudents: 8920,
    baseEngagement: 54.2,
    talukas: ["Palghar", "Vada", "Vikramgad", "Jawhar", "Mokhada", "Dahanu", "Talasari", "Vasai"],
  },
  {
    id: "raigad",
    name: "Raigad",
    code: "RAI",
    division: "Konkan",
    headquarters: "Alibag",
    baseStudents: 9140,
    baseEngagement: 64.5,
    talukas: ["Alibag", "Pen", "Murud", "Panvel", "Uran", "Karjat", "Khalapur", "Mangaon", "Roha", "Sudhagad", "Mahad", "Poladpur", "Shrivardhan", "Mhasla", "Tala"],
  },
  {
    id: "ratnagiri",
    name: "Ratnagiri",
    code: "RTG",
    division: "Konkan",
    headquarters: "Ratnagiri",
    baseStudents: 7420,
    baseEngagement: 65.8,
    talukas: ["Ratnagiri", "Chiplun", "Khed", "Guhagar", "Dapoli", "Mandangad", "Sangameshwar", "Lanja", "Rajapur"],
  },
  {
    id: "sindhudurg",
    name: "Sindhudurg",
    code: "SND",
    division: "Konkan",
    headquarters: "Oros",
    baseStudents: 5210,
    baseEngagement: 68.4,
    talukas: ["Kudal", "Kankavli", "Sawantwadi", "Malvan", "Vengurla", "Devgad", "Vaibhavwadi", "Dodamarg"],
  },

  // --- PUNE DIVISION (5 districts) ---
  {
    id: "pune",
    name: "Pune",
    code: "PUN",
    division: "Pune",
    headquarters: "Pune",
    baseStudents: 22480,
    baseEngagement: 77.8,
    talukas: ["Pune City", "Haveli", "Khed", "Ambegaon", "Junnar", "Shirur", "Daund", "Indapur", "Baramati", "Purandar", "Bhor", "Velhe", "Mulshi", "Maval"],
  },
  {
    id: "satara",
    name: "Satara",
    code: "SAT",
    division: "Pune",
    headquarters: "Satara",
    baseStudents: 8580,
    baseEngagement: 64.6,
    talukas: ["Satara", "Wai", "Khandala", "Phaltan", "Man", "Khatav", "Koregaon", "Patan", "Karad", "Jaoli", "Mahabaleshwar"],
  },
  {
    id: "sangli",
    name: "Sangli",
    code: "SAN",
    division: "Pune",
    headquarters: "Sangli",
    baseStudents: 8120,
    baseEngagement: 66.2,
    talukas: ["Miraj", "Tasgaon", "Khanapur (Vita)", "Atpadi", "Jat", "Kavathe Mahankal", "Walwa (Islampur)", "Shirala", "Kadegaon", "Palus"],
  },
  {
    id: "solapur",
    name: "Solapur",
    code: "SOL",
    division: "Pune",
    headquarters: "Solapur",
    baseStudents: 9860,
    baseEngagement: 58.9,
    talukas: ["Solapur North", "Solapur South", "Barshi", "Akkalkot", "Mohol", "Pandharpur", "Mangalwedha", "Karmala", "Madha", "Malshiras", "Sangola"],
  },
  {
    id: "kolhapur",
    name: "Kolhapur",
    code: "KOL",
    division: "Pune",
    headquarters: "Kolhapur",
    baseStudents: 10380,
    baseEngagement: 69.5,
    talukas: ["Karveer", "Panhala", "Shahuwadi", "Kagal", "Hatkanangale", "Shirol", "Radhanagari", "Gaganbawda", "Bhudargad", "Gadhinglaj", "Chandgad", "Ajra"],
  },

  // --- NASHIK DIVISION (5 districts) ---
  {
    id: "nashik",
    name: "Nashik",
    code: "NAS",
    division: "Nashik",
    headquarters: "Nashik",
    baseStudents: 12840,
    baseEngagement: 67.8,
    talukas: ["Nashik", "Igatpuri", "Dindori", "Peth", "Trimbakeshwar", "Kalwan", "Deola", "Surgana", "Baglan (Satana)", "Malegaon", "Nandgaon", "Chandwad", "Niphad", "Sinnar", "Yeola"],
  },
  {
    id: "dhule",
    name: "Dhule",
    code: "DHU",
    division: "Nashik",
    headquarters: "Dhule",
    baseStudents: 6940,
    baseEngagement: 59.4,
    talukas: ["Dhule", "Sakri", "Sindkheda", "Shirpur"],
  },
  {
    id: "nandurbar",
    name: "Nandurbar",
    code: "NDB",
    division: "Nashik",
    headquarters: "Nandurbar",
    baseStudents: 8240,
    baseEngagement: 47.4,
    talukas: ["Nandurbar", "Navapur", "Shahada", "Taloda", "Akkalkuwa", "Akrani (Dhadgaon)"],
  },
  {
    id: "jalgaon",
    name: "Jalgaon",
    code: "JAL",
    division: "Nashik",
    headquarters: "Jalgaon",
    baseStudents: 10450,
    baseEngagement: 62.1,
    talukas: ["Jalgaon", "Bhusawal", "Yawal", "Raver", "Muktainagar", "Bodwad", "Amalner", "Parola", "Chopda", "Erandol", "Dharangaon", "Pachora", "Bhadgaon", "Chalisgaon", "Jamner"],
  },
  {
    id: "ahilyanagar",
    name: "Ahilyanagar (Ahmednagar)",
    code: "AHI",
    division: "Nashik",
    headquarters: "Ahilyanagar",
    baseStudents: 11980,
    baseEngagement: 65.7,
    talukas: ["Nagar", "Rahuri", "Shrirampur", "Nevasa", "Shevgaon", "Pathardi", "Jamkhed", "Karjat", "Shrigonda", "Parner", "Akole", "Sangamner", "Kopargaon", "Rahta"],
  },

  // --- CHHATRAPATI SAMBHAJINAGAR DIVISION (Marathwada - 8 districts) ---
  {
    id: "sambhajinagar",
    name: "Chhatrapati Sambhajinagar",
    code: "AUR",
    division: "Chhatrapati Sambhajinagar",
    headquarters: "Chhatrapati Sambhajinagar",
    baseStudents: 11560,
    baseEngagement: 65.8,
    talukas: ["Aurangabad", "Kannad", "Soegaon", "Sillod", "Phulambri", "Khuldabad", "Vaijapur", "Gangapur", "Paithan"],
  },
  {
    id: "jalna",
    name: "Jalna",
    code: "JLN",
    division: "Chhatrapati Sambhajinagar",
    headquarters: "Jalna",
    baseStudents: 6840,
    baseEngagement: 56.4,
    talukas: ["Jalna", "Bhokardan", "Jafrabad", "Badnapur", "Ambad", "Ghansawangi", "Partur", "Mantha"],
  },
  {
    id: "parbhani",
    name: "Parbhani",
    code: "PRB",
    division: "Chhatrapati Sambhajinagar",
    headquarters: "Parbhani",
    baseStudents: 6210,
    baseEngagement: 53.8,
    talukas: ["Parbhani", "Gangakhed", "Sonpeth", "Pathri", "Manwath", "Palam", "Selu", "Jintur", "Purna"],
  },
  {
    id: "hingoli",
    name: "Hingoli",
    code: "HIN",
    division: "Chhatrapati Sambhajinagar",
    headquarters: "Hingoli",
    baseStudents: 5740,
    baseEngagement: 45.1,
    talukas: ["Hingoli", "Kalamnuri", "Sengaon", "Aundha Nagnath", "Basmath"],
  },
  {
    id: "nanded",
    name: "Nanded",
    code: "NED",
    division: "Chhatrapati Sambhajinagar",
    headquarters: "Nanded",
    baseStudents: 9850,
    baseEngagement: 57.2,
    talukas: ["Nanded", "Biloli", "Mukhed", "Kandhar", "Loha", "Mudkhed", "Ardhapur", "Bhokar", "Umri", "Dharmabad", "Kinwat", "Himayatnagar", "Hadgaon", "Mahoor", "Deglur", "Naigaon"],
  },
  {
    id: "beed",
    name: "Beed",
    code: "BED",
    division: "Chhatrapati Sambhajinagar",
    headquarters: "Beed",
    baseStudents: 8750,
    baseEngagement: 52.6,
    talukas: ["Beed", "Ashti", "Patoda", "Shirur (Kasar)", "Georai", "Majalgaon", "Wadwani", "Kaij", "Dharur", "Parli (Vaijnath)", "Ambejogai"],
  },
  {
    id: "latur",
    name: "Latur",
    code: "LAT",
    division: "Chhatrapati Sambhajinagar",
    headquarters: "Latur",
    baseStudents: 9120,
    baseEngagement: 68.7,
    talukas: ["Latur", "Ausa", "Renapur", "Ahmedpur", "Chakur", "Shirur Anantpal", "Nilanga", "Deoni", "Udgir", "Jalkot"],
  },
  {
    id: "dharashiv",
    name: "Dharashiv (Osmanabad)",
    code: "DHA",
    division: "Chhatrapati Sambhajinagar",
    headquarters: "Dharashiv",
    baseStudents: 6450,
    baseEngagement: 51.9,
    talukas: ["Dharashiv", "Tuljapur", "Bhum", "Paranda", "Washi", "Kalamb", "Lohara", "Umarga"],
  },

  // --- AMRAVATI DIVISION (Vidarbha - 5 districts) ---
  {
    id: "amravati",
    name: "Amravati",
    code: "AMA",
    division: "Amravati",
    headquarters: "Amravati",
    baseStudents: 9180,
    baseEngagement: 61.7,
    talukas: ["Amravati", "Bhatkuli", "Nandgaon Khandeshwar", "Dharni", "Chikhaldara", "Achalpur", "Chandurbazar", "Morshi", "Warud", "Daryapur", "Anjangaon Surji", "Chandur Railway", "Dhamangaon Railway", "Tiwsa"],
  },
  {
    id: "akola",
    name: "Akola",
    code: "AKL",
    division: "Amravati",
    headquarters: "Akola",
    baseStudents: 7850,
    baseEngagement: 63.4,
    talukas: ["Akola", "Akot", "Telhara", "Balapur", "Patur", "Murtizapur", "Barshitakli"],
  },
  {
    id: "washim",
    name: "Washim",
    code: "WAS",
    division: "Amravati",
    headquarters: "Washim",
    baseStudents: 6420,
    baseEngagement: 43.7,
    talukas: ["Washim", "Malegaon", "Risod", "Mangrulpir", "Karanja", "Manora"],
  },
  {
    id: "buldhana",
    name: "Buldhana",
    code: "BLD",
    division: "Amravati",
    headquarters: "Buldhana",
    baseStudents: 8940,
    baseEngagement: 58.2,
    talukas: ["Buldhana", "Chikhli", "Deulgaon Raja", "Jalgaon Jamod", "Sangrampur", "Malkapur", "Motala", "Nandura", "Khamgaon", "Shegaon", "Mehkar", "Sindkhed Raja", "Lonar"],
  },
  {
    id: "yavatmal",
    name: "Yavatmal",
    code: "YAT",
    division: "Amravati",
    headquarters: "Yavatmal",
    baseStudents: 8950,
    baseEngagement: 49.6,
    talukas: ["Yavatmal", "Arni", "Babhulgaon", "Kalamb", "Darwha", "Digras", "Ner", "Pusad", "Umarkhed", "Mahagaon", "Ghatanji", "Kelapur (Pandharkawada)", "Ralegaon", "Maregaon", "Zari Jamani", "Wani"],
  },

  // --- NAGPUR DIVISION (Vidarbha - 6 districts) ---
  {
    id: "nagpur",
    name: "Nagpur",
    code: "NAG",
    division: "Nagpur",
    headquarters: "Nagpur",
    baseStudents: 14420,
    baseEngagement: 72.9,
    talukas: ["Nagpur Urban", "Nagpur Rural", "Kamptee", "Hingna", "Katol", "Narkhed", "Savner", "Kalmeshwar", "Ramtek", "Mouda", "Parseoni", "Umred", "Kuhi", "Bhiwapur"],
  },
  {
    id: "wardha",
    name: "Wardha",
    code: "WRD",
    division: "Nagpur",
    headquarters: "Wardha",
    baseStudents: 6540,
    baseEngagement: 64.8,
    talukas: ["Wardha", "Deoli", "Seloo", "Arvi", "Ashti", "Karanja", "Hinganghat", "Samudrapur"],
  },
  {
    id: "bhandara",
    name: "Bhandara",
    code: "BHA",
    division: "Nagpur",
    headquarters: "Bhandara",
    baseStudents: 5890,
    baseEngagement: 62.4,
    talukas: ["Bhandara", "Tumsar", "Pauni", "Mohadi", "Sakoli", "Lakhani", "Lakhandur"],
  },
  {
    id: "gondia",
    name: "Gondia",
    code: "GON",
    division: "Nagpur",
    headquarters: "Gondia",
    baseStudents: 5920,
    baseEngagement: 59.8,
    talukas: ["Gondia", "Tirora", "Goregaon", "Amgaon", "Salekasa", "Sadak Arjuni", "Arjuni Morgaon", "Deori"],
  },
  {
    id: "chandrapur",
    name: "Chandrapur",
    code: "CHA",
    division: "Nagpur",
    headquarters: "Chandrapur",
    baseStudents: 7480,
    baseEngagement: 55.8,
    talukas: ["Chandrapur", "Bhadravati", "Warora", "Chimur", "Nagbhir", "Bramhapuri", "Sindewahi", "Mul", "Sawali", "Gondpipri", "Korpurna", "Rajura", "Jivati", "Ballarpur", "Pombhurna"],
  },
  {
    id: "gadchiroli",
    name: "Gadchiroli",
    code: "GAD",
    division: "Nagpur",
    headquarters: "Gadchiroli",
    baseStudents: 5980,
    baseEngagement: 42.7,
    talukas: ["Gadchiroli", "Dhanora", "Chamorshi", "Armori", "Kurkheda", "Korchi", "Desaiganj (Wadsa)", "Aheri", "Etapalli", "Bhamragad", "Sironcha", "Mulchera"],
  },
];
