/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentAnalyticsRouteImport } from './routes/assessment-analytics'
import { Route as DistrictAnalyticsRouteImport } from './routes/district-analytics'
import { Route as LearningProgramsRouteImport } from './routes/learning-programs'
import { Route as ReportsRouteImport } from './routes/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentAnalyticsRoute = AssessmentAnalyticsRouteImport.update({
  id: '/assessment-analytics',
  path: '/assessment-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictAnalyticsRoute = DistrictAnalyticsRouteImport.update({
  id: '/district-analytics',
  path: '/district-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningProgramsRoute = LearningProgramsRouteImport.update({
  id: '/learning-programs',
  path: '/learning-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment-analytics': typeof AssessmentAnalyticsRoute
  '/district-analytics': typeof DistrictAnalyticsRoute
  '/learning-programs': typeof LearningProgramsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment-analytics': typeof AssessmentAnalyticsRoute
  '/district-analytics': typeof DistrictAnalyticsRoute
  '/learning-programs': typeof LearningProgramsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment-analytics': typeof AssessmentAnalyticsRoute
  '/district-analytics': typeof DistrictAnalyticsRoute
  '/learning-programs': typeof LearningProgramsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment-analytics'
    | '/district-analytics'
    | '/learning-programs'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment-analytics'
    | '/district-analytics'
    | '/learning-programs'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/assessment-analytics'
    | '/district-analytics'
    | '/learning-programs'
    | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentAnalyticsRoute: typeof AssessmentAnalyticsRoute
  DistrictAnalyticsRoute: typeof DistrictAnalyticsRoute
  LearningProgramsRoute: typeof LearningProgramsRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment-analytics': {
      id: '/assessment-analytics'
      path: '/assessment-analytics'
      fullPath: '/assessment-analytics'
      preLoaderRoute: typeof AssessmentAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district-analytics': {
      id: '/district-analytics'
      path: '/district-analytics'
      fullPath: '/district-analytics'
      preLoaderRoute: typeof DistrictAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-programs': {
      id: '/learning-programs'
      path: '/learning-programs'
      fullPath: '/learning-programs'
      preLoaderRoute: typeof LearningProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentAnalyticsRoute: AssessmentAnalyticsRoute,
  DistrictAnalyticsRoute: DistrictAnalyticsRoute,
  LearningProgramsRoute: LearningProgramsRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
