/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedAssessmentAnalyticsRouteImport } from './routes/_authenticated/assessment-analytics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDistrictAnalyticsRouteImport } from './routes/_authenticated/district-analytics'
import { Route as AuthenticatedLearningProgramsRouteImport } from './routes/_authenticated/learning-programs'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'

const AuthenticatedAssessmentAnalyticsRoute =
  AuthenticatedAssessmentAnalyticsRouteImport.update({
    id: '/_authenticated/assessment-analytics',
    path: '/assessment-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDistrictAnalyticsRoute =
  AuthenticatedDistrictAnalyticsRouteImport.update({
    id: '/_authenticated/district-analytics',
    path: '/district-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLearningProgramsRoute =
  AuthenticatedLearningProgramsRouteImport.update({
    id: '/_authenticated/learning-programs',
    path: '/learning-programs',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/_authenticated/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/assessment-analytics': typeof AuthenticatedAssessmentAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/district-analytics': typeof AuthenticatedDistrictAnalyticsRoute
  '/learning-programs': typeof AuthenticatedLearningProgramsRoute
  '/reports': typeof AuthenticatedReportsRoute
}
export interface FileRoutesByTo {
  '/assessment-analytics': typeof AuthenticatedAssessmentAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/district-analytics': typeof AuthenticatedDistrictAnalyticsRoute
  '/learning-programs': typeof AuthenticatedLearningProgramsRoute
  '/reports': typeof AuthenticatedReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/assessment-analytics': typeof AuthenticatedAssessmentAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/district-analytics': typeof AuthenticatedDistrictAnalyticsRoute
  '/_authenticated/learning-programs': typeof AuthenticatedLearningProgramsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/assessment-analytics'
    | '/dashboard'
    | '/district-analytics'
    | '/learning-programs'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assessment-analytics'
    | '/dashboard'
    | '/district-analytics'
    | '/learning-programs'
    | '/reports'
  id:
    | '__root__'
    | '/_authenticated/assessment-analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/district-analytics'
    | '/_authenticated/learning-programs'
    | '/_authenticated/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAssessmentAnalyticsRoute: typeof AuthenticatedAssessmentAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistrictAnalyticsRoute: typeof AuthenticatedDistrictAnalyticsRoute
  AuthenticatedLearningProgramsRoute: typeof AuthenticatedLearningProgramsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/assessment-analytics': {
      id: '/_authenticated/assessment-analytics'
      path: '/assessment-analytics'
      fullPath: '/assessment-analytics'
      preLoaderRoute: typeof AuthenticatedAssessmentAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/district-analytics': {
      id: '/_authenticated/district-analytics'
      path: '/district-analytics'
      fullPath: '/district-analytics'
      preLoaderRoute: typeof AuthenticatedDistrictAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learning-programs': {
      id: '/_authenticated/learning-programs'
      path: '/learning-programs'
      fullPath: '/learning-programs'
      preLoaderRoute: typeof AuthenticatedLearningProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAssessmentAnalyticsRoute: AuthenticatedAssessmentAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistrictAnalyticsRoute: AuthenticatedDistrictAnalyticsRoute,
  AuthenticatedLearningProgramsRoute: AuthenticatedLearningProgramsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
